spring:
  # TODO: 导入common配置到其他模块，以后所有模块更改，都需要同步更新
  profiles:
    active: chat, hotel, online, physical, start, user
  datasource:
    url: jdbc:mysql://localhost:3306/pipayshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  basic:
    enable: true
  setting:
    language: zh_cn
server:
  servlet:
    context-path: /api
  port: 7125
